# Generated by Django 4.1.5 on 2023-01-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_username_advocate_usernam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='usernam',
            new_name='username',
        ),
    ]
